### ISSUE TITLE
Give this repo a name that isn't stupid

### ISSUE THREAD

**Issue by kylediaz** [frc3624/test-temporary#4]
you're a loser

**Comment by GeoDash897** [comment]
@Haadi-Khan yeah bro, fix this. It looks *trash*

**Comment by Haadi-Khan** [comment]
BRUH

**Comment by Haadi-Khan** [comment]
@GeoDash897 YOU LOOK TRASH

**Comment by GeoDash897** [comment]
but really, please get this done- *It's been open since November*

**Comment by GeoDash897** [comment]
I also @ you and a couple of people in the issues on infinite recharge, make sure to go check that out

**Comment by Haadi-Khan** [comment]
I don't even remember what this repo was for ngl lol

**Comment by GeoDash897** [comment]
Gear shift lesson

**Comment by GeoDash897** [comment]
bro it was your OWN REPO.

**Comment by Haadi-Khan** [comment]
WHAT
Ok there's no way this was gear shift bc gear shift was literally just markdowns

**Comment by Haadi-Khan** [comment]
I think this was when you made us write Drive subsystems and commands and you wanted us to put it on github, and then I was like the only one who actually did that

**Comment by GeoDash897** [comment]
yeah, I just realized it...my bad

**Comment by Haadi-Khan** [comment]
lmfao nice

**Comment by GeoDash897** [comment]
I'll change the name so like its your version of the robot code.

**Comment by GeoDash897** [comment]
do you want to use this as repo to store your version of robot code or just delete it?

**Comment by Haadi-Khan** [comment]
nah just delete it, we'll use a different repo when the time comes
